version: "2"
services:

  zookeeper-1:
    container_name: zookeeper-1    
    networks: ["vnet"]
    hostname: zookeeper-1.vnet
    image: smizy/zookeeper:3.4-alpine
    environment:
      - SERVICE_2181_NAME=zookeeper
      - SERVICE_2888_IGNORE=true
      - SERVICE_3888_IGNORE=true
      
    command: -server 1 3 vnet

  zookeeper-2:
    container_name: zookeeper-2    
    networks: ["vnet"]
    hostname: zookeeper-2.vnet
    image: smizy/zookeeper:3.4-alpine
    environment:
      - SERVICE_2181_NAME=zookeeper
      - SERVICE_2888_IGNORE=true
      - SERVICE_3888_IGNORE=true
      
    command: -server 2 3 vnet

  zookeeper-3:
    container_name: zookeeper-3    
    networks: ["vnet"]
    hostname: zookeeper-3.vnet
    image: smizy/zookeeper:3.4-alpine
    environment:
      - SERVICE_2181_NAME=zookeeper
      - SERVICE_2888_IGNORE=true
      - SERVICE_3888_IGNORE=true
      
    command: -server 3 3 vnet

  journalnode-1:
    container_name: journalnode-1
    networks: ["vnet"]
    hostname: journalnode-1.vnet
    image: smizy/hadoop-base:2.7.3-alpine
    expose: [8480, 8485]
    environment:
      - SERVICE_8485_NAME=journalnode
      - SERVICE_8480_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      
    command: journalnode

  journalnode-2:
    container_name: journalnode-2
    networks: ["vnet"]
    hostname: journalnode-2.vnet
    image: smizy/hadoop-base:2.7.3-alpine
    expose: [8480, 8485]
    environment:
      - SERVICE_8485_NAME=journalnode
      - SERVICE_8480_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      
    command: journalnode

  journalnode-3:
    container_name: journalnode-3
    networks: ["vnet"]
    hostname: journalnode-3.vnet
    image: smizy/hadoop-base:2.7.3-alpine
    expose: [8480, 8485]
    environment:
      - SERVICE_8485_NAME=journalnode
      - SERVICE_8480_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      
    command: journalnode

  namenode-1:
    container_name: namenode-1
    networks: ["vnet"]
    hostname: namenode-1.vnet
    image: smizy/hadoop-base:2.7.3-alpine 
    expose: ["8020"]
    ports:  ["50070"]
    environment:
      - SERVICE_8020_NAME=namenode
      - SERVICE_50070_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      
    entrypoint: entrypoint.sh
    command: namenode-1

  namenode-2:
    container_name: namenode-2
    networks: ["vnet"]
    hostname: namenode-2.vnet
    image: smizy/hadoop-base:2.7.3-alpine 
    expose: ["8020"]
    ports:  ["50070"]
    environment:
      - SERVICE_8020_NAME=namenode
      - SERVICE_50070_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      
    entrypoint: entrypoint.sh
    command: namenode-2

  datanode-1:
    container_name: datanode-1
    networks: ["vnet"]
    hostname: datanode-1.vnet
    image: smizy/hadoop-base:2.7.3-alpine
    expose: ["50010", "50020", "50075"]
    environment:
      - SERVICE_50010_NAME=datanode
      - SERVICE_50020_IGNORE=true
      - SERVICE_50075_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      
    entrypoint: entrypoint.sh
    command: datanode

  datanode-2:
    container_name: datanode-2
    networks: ["vnet"]
    hostname: datanode-2.vnet
    image: smizy/hadoop-base:2.7.3-alpine
    expose: ["50010", "50020", "50075"]
    environment:
      - SERVICE_50010_NAME=datanode
      - SERVICE_50020_IGNORE=true
      - SERVICE_50075_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      
    entrypoint: entrypoint.sh
    command: datanode

  datanode-3:
    container_name: datanode-3
    networks: ["vnet"]
    hostname: datanode-3.vnet
    image: smizy/hadoop-base:2.7.3-alpine
    expose: ["50010", "50020", "50075"]
    environment:
      - SERVICE_50010_NAME=datanode
      - SERVICE_50020_IGNORE=true
      - SERVICE_50075_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      
    entrypoint: entrypoint.sh
    command: datanode

  resourcemanager-1:
    container_name: resourcemanager-1
    networks: ["vnet"]
    hostname: resourcemanager-1.vnet
    image: smizy/hadoop-base:2.7.3-alpine
    expose: ["8030-8033"]
    ports:  ["8088"]
    environment:
      - SERVICE_8088_NAME=resourcemanager
      - SERVICE_8030_IGNORE=true
      - SERVICE_8031_IGNORE=true
      - SERVICE_8032_IGNORE=true
      - SERVICE_8033_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      
    entrypoint: entrypoint.sh
    command: resourcemanager-1

  historyserver-1:
    container_name: historyserver-1
    networks: ["vnet"]
    hostname: historyserver-1.vnet
    image: smizy/hadoop-base:2.7.3-alpine
    expose: ["10020"]
    ports:  ["19888:19888"]
    environment:
      - SERVICE_19888_NAME=historyserver
      - SERVICE_10020_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      
    entrypoint: entrypoint.sh
    command: historyserver-1

  nodemanager-1:
    container_name: nodemanager-1
    networks: ["vnet"]
    hostname: nodemanager-1.vnet
    image: smizy/hadoop-base:2.7.3-alpine
    expose: ["8040-8042"]
    environment:
      - SERVICE_8042_NAME=nodemanager
      - SERVICE_8040_IGNORE=true
      - SERVICE_8041_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      
    entrypoint: entrypoint.sh
    command: nodemanager

  nodemanager-2:
    container_name: nodemanager-2
    networks: ["vnet"]
    hostname: nodemanager-2.vnet
    image: smizy/hadoop-base:2.7.3-alpine
    expose: ["8040-8042"]
    environment:
      - SERVICE_8042_NAME=nodemanager
      - SERVICE_8040_IGNORE=true
      - SERVICE_8041_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      
    entrypoint: entrypoint.sh
    command: nodemanager

  nodemanager-3:
    container_name: nodemanager-3
    networks: ["vnet"]
    hostname: nodemanager-3.vnet
    image: smizy/hadoop-base:2.7.3-alpine
    expose: ["8040-8042"]
    environment:
      - SERVICE_8042_NAME=nodemanager
      - SERVICE_8040_IGNORE=true
      - SERVICE_8041_IGNORE=true
      - HADOOP_ZOOKEEPER_QUORUM=zookeeper-1.vnet:2181,zookeeper-2.vnet:2181,zookeeper-3.vnet:2181 
      
    entrypoint: entrypoint.sh
    command: nodemanager

networks:
  vnet:
    external:
      name: vnet 
